imports:
    - { resource: "services.yml" }

parameters:
    kyela_version: 1.6.9

framework:
    translator: { fallback: en }

twig:
    form:
        resources:
            - 'KyelaBundle:Form:fields.html.twig'
    globals:
        kyela_version: '%kyela_version%'
