imports:
    - { resource: "services.yml" }

framework:
    translator: { fallback: en }

twig:
    form:
        resources:
            - 'KyelaBundle:Form:fields.html.twig'
    globals:
        app_version: '%app_version%'
