imports:
    - { resource: "parameters.yml" }
    - { resource: "services.yml" }

framework:
    translator: { fallback: en }

twig:
    form:
        resources:
            - 'KyelaBundle:Form:fields.html.twig'
