imports:
    - { resource: "services.yml" }

parameters:
    kyela_version: 1.7.1

framework:
    translator: { fallback: en }

twig:
    form_themes:
        - 'KyelaBundle:form:fields.html.twig'
    globals:
        kyela_version: '%kyela_version%'
