kyela_main:
    resource: "@KyelaBundle/Controller/MainController.php"
    type: annotation
    prefix: /kyela

kyela_participant:
    resource: "@KyelaBundle/Controller/ParticipantController.php"
    type: annotation
    prefix: /kyela

kyela_event:
    resource: "@KyelaBundle/Controller/EventController.php"
    type: annotation
    prefix: /kyela
