kyela_robots:
    path: /robots.txt
    defaults:
        _controller: FrameworkBundle:Template:template
        _format: txt
        template: KyelaBundle:Static:robots.txt.twig

kyela_application:
    resource: "@KyelaBundle/Controller"
    type: annotation
    prefix: /
