services:
    abienvenu.kyela.form.type.form_actions:
        class: Abienvenu\KyelaBundle\Form\Type\FormActionsType
        tags:
            - { name: form.type, alias: form_actions }

    abienvenu.kyela.action_listener:
        class: Abienvenu\KyelaBundle\EventListener\PollUrlListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    abienvenu.kyela.locale_listener:
        class: Abienvenu\KyelaBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
