services:
    abienvenu.kyela.form.type.form_actions:
        class: Abienvenu\KyelaBundle\Form\FormActionsType
        tags:
            - { name: form.type, alias: form_actions }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
