services:
    abienvenu.kyela.action_listener:
        class: Abienvenu\KyelaBundle\EventListener\PollUrlListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    abienvenu.kyela.locale_listener:
        class: Abienvenu\KyelaBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    abienvenu.kyela.crawler_listener:
        class: Abienvenu\KyelaBundle\EventListener\CrawlerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
