default:
    extensions:
        Behat\MinkExtension:
            base_url: "http://172.17.0.1:8042/"
            goutte:
            selenium2:
                wd_host: "http://172.17.0.1:4444/wd/hub"
                capabilities:
                    marionette: null
            browser_name: chrome
        Behat\Symfony2Extension:
            kernel:
                env: test
                debug: true
        Behatch\Extension: ~

    suites:
        default:
            contexts:
                - Behat\MinkExtension\Context\MinkContext
                - Behatch\Context\DebugContext:
                    screenshotDir: "/tmp/behat_screenshots"
                - Behatch\Context\BrowserContext
                - Abienvenu\KyelaBundle\Tests\Behat\Context\KyelaContext

            paths:
                - "%paths.base%/src/Abienvenu/KyelaBundle/Tests/Behat/Feature"
