doctrine:
    dbal:
        driver: 'pdo_sqlite'
        charset: UTF8
        host:     '127.0.0.1'
        dbname:   'kyela'
        path:     '%kernel.project_dir%/data/kyela.db3'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
