imports:
    - { resource: "@KyelaBundle/Resources/config/config.yml" }

parameters:
    secret: ea1a820d86d611769f193ffc2bea917ea2396043
    locale: fr

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ KyelaBundle ]
    filters:
        cssrewrite: ~
    read_from:            '%kernel.project_dir%'
    write_to:             '%kernel.project_dir%/public'
